# Generated by Django 3.2.8 on 2021-11-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirdropUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('twitter_username', models.CharField(max_length=20)),
                ('telegram_username', models.CharField(max_length=20)),
                ('discord_username', models.CharField(blank=True, max_length=20, null=True)),
                ('tweet_link', models.CharField(max_length=100)),
                ('trx_address', models.CharField(max_length=100)),
            ],
        ),
    ]
