# Generated by Django 3.2.8 on 2021-11-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airdropusers',
            name='tweet_link',
            field=models.URLField(max_length=100),
        ),
    ]
